version: '3'
services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d

  was:
    container_name: was
    restart: always
    build:
      context: ./was
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root1234!
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d